### ISSUE TITLE
thanks for prices but....

### ISSUE THREAD

**Issue by ykokam2** [giventofly/mkmapi-php#2]
I only have appToken and appSecret for widget access, but i obtain error 403. 
i change this:
//encode to sigkey
  //$signatureKey = rawurlencode($appSecret) . "&" . rawurlencode($accessSecret);
  //widget app doesn't attach the access Secret, uncomment to use it
  $signatureKey = rawurlencode($appSecret) . "&";
but error persist.
Can you helpme?
--------
Como creo que sabes español y me explico mejor, te lo cuento tambien en este idioma.
Al buscar una carta siempre me da el error 403 que segun la documentacion es que no tengo acceso, solo tengo de momento el appSecret y el appToken (pedidos para un widget).
Segun la documentacion con el appSecret seria suficiente, pero aun cambiando esa parte del codigo, sigue saliendo el error 403.

Un Saludo.

Por cierto, mil millones de gracias por compartir esto.

**Comment by giventofly** [comment]
Actually i'm portuguese not spanish :) but i understand spanish too.

I also have an widget app and i'm using that code in production (with minor alterations) so it should be working. You let $accesstoken and $accessSecret = ""; ?

My suggestion would be to contact directly cardmarket support and they can help you further because i'm using the exact same code with a widget app and its working.

sorry i can't help further

**Comment by ykokam2** [comment]
i alrready found the problem, i set the appSecret and appToken  in the beggin of program, but this values not reconized in the function, i set the variables in correct place and now working.
thanks!!!!

**Comment by giventofly** [comment]
nice :) :+1:
